---
# file elkstack.yml
- hosts: all
  become: true
  become_method: sudo

  vars_files:
   - vars/default.yml

  roles:
    - { role: environment, tags: ["always"] }
    - { role: elasticsearch, tags: ["elasticsearch"] }
    - { role: logstash, tags: [logstash] }
    - { role: kibana, tags: [kibana] }
