disable_selinux: "False"
elasticsearch_version: "2.1"
elasticsearch_network_host: "127.0.0.1"

logstash_version: "2.1"
logstash_patterns_dir: "/etc/logstash/patterns/"
logstash_syslog_port_tcp: "5000"
logstash_syslog_port_udp: "5000"

kibana_version: "4.3.1-linux-x64"
kibana_dir: "/opt/kibana/"

kibana_url: "https://download.elasticsearch.org/kibana/kibana/kibana-{{ kibana_version }}.tar.gz"
